---
title: "Data Engineering Demo 05"
subtitle: "Some subtitle"
date: today
author: "Karol"
format: 
  html:
    toc: true
    toc-location: right
    toc-title: "Yes"
    code-link: true
    code-tools: true
    embed-resources: true
    self-contained-math: true
  pdf: 
    toc: true
    toc-title: "Inhaltsverzeichnis"
    number-sections: true
  revealjs: 
    echo: fenced
editor: source
---

## Overview

* Create ggplot graphs with helper packages
* Packages: `{esquisse}` and `{ggrapR}`

## Libraries

```{r}
library(esquissse)
library(ggraptR)
```
```{r}
esquisse::esquisser(data=iris)
```


## Make a pairs plot
```{r}
pairs(iris, col=iris$s)
```


```{r}
ggraptR::ggraptR(iris)
```


## Copy interactice code 
* use pairs as plot type (need to field to get pairs option)

```{r}
ggpairs(
  iris,
  mapping = aes(colour = Species, alpha = 0.5),
  columns = c(
    "Sepal.Length",
    "Sepal.Width",
    "Petal.Length",
    "Petal.Width",
    "Species"
  ),
  upper = list(
    continuous = "cor",
    combo = "box",
    discrete = "facetbar"
  ),
  diag = list(continuous = "densityDiag", discrete = "barDiag"),
  lower = list(
    continuous = "points",
    combo = "facethist",
    discrete = "facetbar"
  )
)
ggpairs(
  iris,
  mapping = aes(alpha = 0.5),
  columns = c(
    "Sepal.Length",
    "Sepal.Width",
    "Petal.Length",
    "Petal.Width",
    "Species"
  ),
  upper = list(
    continuous = "cor",
    combo = "box",
    discrete = "facetbar"
  ),
  diag = list(continuous = "densityDiag", discrete = "barDiag"),
  lower = list(
    continuous = "points",
    combo = "facethist",
    discrete = "facetbar"
  )
)
ggpairs(
  iris,
  mapping = aes(alpha = 0.5),
  columns = c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"),
  upper = list(
    continuous = "cor",
    combo = "box",
    discrete = "facetbar"
  ),
  diag = list(continuous = "densityDiag", discrete = "barDiag"),
  lower = list(
    continuous = "points",
    combo = "facethist",
    discrete = "facetbar"
  )
)
ggpairs(
  iris,
  mapping = aes(alpha = 0.5),
  columns = c("Sepal.Length", "Sepal.Width", "Petal.Length"),
  upper = list(
    continuous = "cor",
    combo = "box",
    discrete = "facetbar"
  ),
  diag = list(continuous = "densityDiag", discrete = "barDiag"),
  lower = list(
    continuous = "points",
    combo = "facethist",
    discrete = "facetbar"
  )
)
ggplot(iris, aes(y = Sepal.Width, x = Sepal.Length)) + geom_point(
  stat = "identity",
  position = "jitter",
  alpha = 0.5,
  size = 3
) + theme_grey() + theme(text = element_text(
  family = "sans",
  face = "plain",
  color = "#000000",
  size = 15,
  hjust = 0.5,
  vjust = 0.5
)) + scale_size(range = c(1, 3)) + xlab("Sepal.Length") + ylab("Sepal.Width")

```

## mtcars efficiency per kilogram

```{r}
data <- mtcars %>%  mutate(efficiency = mpg/wt, .before = cyl)
data$am <- ifelse(data$am == 0, "Automatik", "Manuell")
ggraptR::ggraptR(data)
```






